version: '3.8'
services:
  nginx:
    container_name: "nginx"
    image: nginx:1.19
    ports:
      - "800:80"
    volumes:
      - ./html:/usr/share/nginx/html

  curl:
    container_name: "curl"
    build:
      context: .
      dockerfile: Dockerfile

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
